### ISSUE TITLE
All URLs with an 'x' are rejected in regex? 

### ISSUE THREAD

**Issue by tsaltena** [LSmyrnaios/PublicationsRetriever#14]
Hi Lampros,

Have been benefitting from this package greatly, many thanks for developing it. In checking why some of my PDF downloads were unsuccesful, a common reason appeared to be:

`Discarded after matching to unwantedType-regex-rules.`

I tried to replicate some of the regex rules, and the |x| here seems to be the culprit:
https://github.com/LSmyrnaios/PublicationsRetriever/blob/fec27dc75c151d88730a621a179506612169594f/src/main/java/eu/openaire/publications_retriever/util/url/UrlTypeChecker.java#L56

This causes all URLs with an x in it to fail (all arxives, but also ieeexplore, exeter university, etc.)

Would it make sense to turn that 'x' into 'x.co' or something?

Many thanks again for this package,
Tijmen

**Comment by LSmyrnaios** [comment]
Thank you Tijmen for reporting this bug!
Indeed the addition of blocking urls of the new Tweeter's domain "x" was not implemented correctly.

I believe [this commit](https://github.com/LSmyrnaios/PublicationsRetriever/commit/bc1b1ff6e0317e1fcda993aa83ba987a7716abdb) fixes it and prevents some other false-positives as well.

Please test it and verify that your use-cases work as expected.

**Comment by tsaltena** [comment]
Hi Lampros, 
Many thanks for this blazingly fast fix! This indeed fixes the downloader for my usecases. Please feel free to close the issue.
Best,
Tijmen
