### ISSUE TITLE
Outdated snapshot version in runExample.sh

### ISSUE THREAD

**Issue by pkoloveas** [LSmyrnaios/PublicationsRetriever#15]
In the current master branch, the `pom.xml` generates the `publications_retriever-1.2-SNAPSHOT.jar` file. However, the runExample.sh script still has `publications_retriever-1.1-SNAPSHOT.jar`, resulting in the following error when running the script:

`Error: Unable to access jarfile publications_retriever-1.1-SNAPSHOT.jar`

**Comment by LSmyrnaios** [comment]
Thank you @pkoloveas , it was fixed in commit: https://github.com/LSmyrnaios/PublicationsRetriever/commit/1bf0955ac15fe867dd6bf05027c3227ce54f2387
